<?php
declare(strict_types=1);

/**
 * Adds a metabox to posts showing AutoBlogger generation metadata.
 *
 * Only appears on posts that were generated by AutoBlogger (checked via
 * _autoblogger_generated post meta).
 *
 * Triggered by: Autoblogger::register_admin_hooks() on `add_meta_boxes`.
 * Dependencies: WordPress post meta API.
 *
 * @see class-autoblogger.php     — Registers the hook.
 * @see core/class-publisher.php  — Writes the metadata this class displays.
 */
class Autoblogger_Post_Metabox {

	/**
	 * Register the metabox for the post editor.
	 *
	 * @return void
	 */
	public function on_register_metabox(): void {
		$screen = get_current_screen();
		if ( ! $screen || 'post' !== $screen->id ) {
			return;
		}

		global $post;
		if ( ! $post || '1' !== get_post_meta( $post->ID, '_autoblogger_generated', true ) ) {
			return;
		}

		add_meta_box(
			'autoblogger_generation_info',
			__( 'AutoBlogger Generation Info', 'autoblogger' ),
			[ $this, 'render_metabox' ],
			'post',
			'side',
			'default'
		);
	}

	/**
	 * Render the generation metadata metabox.
	 *
	 * @param \WP_Post $post
	 *
	 * @return void
	 */
	public function render_metabox( \WP_Post $post ): void {
		include AUTOBLOGGER_PLUGIN_DIR . 'templates/admin/metabox-generation-info.php';
	}
}
